# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: iamlordaubrey
description: "Spilling my guts; Letting 'em out!"
keywords: "Jekyll, SEO, blog, web, programming, developer, software"
url: https://iamlordaubrey.github.io
baseurl: ""

google_analytics: UA-00000000-0
repo: https://github.com/iamlordaubrey/
disqus_shortname: "aaaaaaaaaaa"
disqus_site_shortname: "aaaaaaaaaaa"

# Author settings
author:
  name: Chiemeka Alim
  job: Software Developer
  bio: "Geek-in-the-making, realistic dreamer, student of Hogwarts, Jedi knight, star gazer and believer in other forms of life."
  thumb: /images/author.jpg
  email: lord.chiemy@gmail.com
  url: https://iamlordaubrey.github.io
  github: https://github.com/iamlordaubrey
  twitter: https://twitter.com/iamlordaubrey
  facebook: https://facebook.com/iamlordaubrey
  linkedin: https://www.linkedin.com/in/chiemekaalim/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
